// Code generated by stanc v2.33.1
#include <stan/model/model_header.hpp>
namespace car_model_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 43> locations_array__ =
  {" (found before start of program)",
  " (in 'car_model.stan', line 13, column 2 to column 17)",
  " (in 'car_model.stan', line 14, column 2 to column 24)",
  " (in 'car_model.stan', line 15, column 2 to column 22)",
  " (in 'car_model.stan', line 16, column 2 to column 20)",
  " (in 'car_model.stan', line 17, column 2 to column 29)",
  " (in 'car_model.stan', line 21, column 2 to column 40)",
  " (in 'car_model.stan', line 25, column 2 to column 23)",
  " (in 'car_model.stan', line 26, column 2 to column 23)",
  " (in 'car_model.stan', line 27, column 2 to column 23)",
  " (in 'car_model.stan', line 28, column 2 to column 21)",
  " (in 'car_model.stan', line 32, column 4 to column 16)",
  " (in 'car_model.stan', line 51, column 8 to column 38)",
  " (in 'car_model.stan', line 49, column 13 to line 52, column 7)",
  " (in 'car_model.stan', line 36, column 15 to column 31)",
  " (in 'car_model.stan', line 36, column 8 to column 44)",
  " (in 'car_model.stan', line 39, column 10 to column 48)",
  " (in 'car_model.stan', line 40, column 10 to column 19)",
  " (in 'car_model.stan', line 38, column 38 to line 41, column 9)",
  " (in 'car_model.stan', line 38, column 8 to line 41, column 9)",
  " (in 'car_model.stan', line 44, column 8 to column 45)",
  " (in 'car_model.stan', line 47, column 8 to column 70)",
  " (in 'car_model.stan', line 35, column 32 to line 49, column 7)",
  " (in 'car_model.stan', line 35, column 6 to line 52, column 7)",
  " (in 'car_model.stan', line 33, column 19 to line 53, column 5)",
  " (in 'car_model.stan', line 33, column 4 to line 53, column 5)",
  " (in 'car_model.stan', line 31, column 2 to line 54, column 3)",
  " (in 'car_model.stan', line 57, column 2 to column 40)",
  " (in 'car_model.stan', line 2, column 2 to column 17)",
  " (in 'car_model.stan', line 3, column 2 to column 17)",
  " (in 'car_model.stan', line 4, column 9 to column 10)",
  " (in 'car_model.stan', line 4, column 2 to column 14)",
  " (in 'car_model.stan', line 5, column 9 to column 10)",
  " (in 'car_model.stan', line 5, column 12 to column 13)",
  " (in 'car_model.stan', line 5, column 2 to column 17)",
  " (in 'car_model.stan', line 7, column 2 to column 23)",
  " (in 'car_model.stan', line 8, column 8 to column 15)",
  " (in 'car_model.stan', line 8, column 2 to column 34)",
  " (in 'car_model.stan', line 9, column 8 to column 9)",
  " (in 'car_model.stan', line 9, column 2 to column 38)",
  " (in 'car_model.stan', line 13, column 9 to column 10)",
  " (in 'car_model.stan', line 14, column 9 to column 10)",
  " (in 'car_model.stan', line 21, column 9 to column 10)"};
class car_model_model final : public model_base_crtp<car_model_model> {
 private:
  int N;
  int P;
  Eigen::Matrix<double,-1,1> y_data__;
  Eigen::Matrix<double,-1,-1> X_data__;
  int N_edges;
  std::vector<int> adj;
  std::vector<int> num_neighbors;
  Eigen::Map<Eigen::Matrix<double,-1,1>> y{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X{nullptr, 0, 0};
 public:
  ~car_model_model() {}
  car_model_model(stan::io::var_context& context__, unsigned int
                  random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "car_model_model_namespace::car_model_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 28;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 28;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 28;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 29;
      context__.validate_dims("data initialization", "P", "int",
        std::vector<size_t>{});
      P = std::numeric_limits<int>::min();
      current_statement__ = 29;
      P = context__.vals_i("P")[(1 - 1)];
      current_statement__ = 29;
      stan::math::check_greater_or_equal(function__, "P", P, 1);
      current_statement__ = 30;
      stan::math::validate_non_negative_index("y", "N", N);
      current_statement__ = 31;
      context__.validate_dims("data initialization", "y", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      y_data__ = Eigen::Matrix<double,-1,1>::Constant(N,
                   std::numeric_limits<double>::quiet_NaN());
      new (&y) Eigen::Map<Eigen::Matrix<double,-1,1>>(y_data__.data(), N);
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 31;
        y_flat__ = context__.vals_r("y");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          stan::model::assign(y, y_flat__[(pos__ - 1)],
            "assigning variable y", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 32;
      stan::math::validate_non_negative_index("X", "N", N);
      current_statement__ = 33;
      stan::math::validate_non_negative_index("X", "P", P);
      current_statement__ = 34;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(P)});
      X_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, P,
                   std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_data__.data(), N, P);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 34;
        X_flat__ = context__.vals_r("X");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 35;
      context__.validate_dims("data initialization", "N_edges", "int",
        std::vector<size_t>{});
      N_edges = std::numeric_limits<int>::min();
      current_statement__ = 35;
      N_edges = context__.vals_i("N_edges")[(1 - 1)];
      current_statement__ = 35;
      stan::math::check_greater_or_equal(function__, "N_edges", N_edges, 1);
      current_statement__ = 36;
      stan::math::validate_non_negative_index("adj", "N_edges", N_edges);
      current_statement__ = 37;
      context__.validate_dims("data initialization", "adj", "int",
        std::vector<size_t>{static_cast<size_t>(N_edges)});
      adj = std::vector<int>(N_edges, std::numeric_limits<int>::min());
      current_statement__ = 37;
      adj = context__.vals_i("adj");
      current_statement__ = 37;
      stan::math::check_greater_or_equal(function__, "adj", adj, 1);
      current_statement__ = 38;
      stan::math::validate_non_negative_index("num_neighbors", "N", N);
      current_statement__ = 39;
      context__.validate_dims("data initialization", "num_neighbors", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      num_neighbors = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 39;
      num_neighbors = context__.vals_i("num_neighbors");
      current_statement__ = 39;
      stan::math::check_greater_or_equal(function__, "num_neighbors",
        num_neighbors, 0);
      current_statement__ = 40;
      stan::math::validate_non_negative_index("beta", "P", P);
      current_statement__ = 41;
      stan::math::validate_non_negative_index("spatial_raw", "N", N);
      current_statement__ = 42;
      stan::math::validate_non_negative_index("spatial", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = P + N + 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "car_model_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.33.1",
             "stancflags = --filename-in-msg=car_model.stan"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "car_model_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__);
      current_statement__ = 1;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(P);
      Eigen::Matrix<local_scalar_t__,-1,1> spatial_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 2;
      spatial_raw = in__.template read<
                      Eigen::Matrix<local_scalar_t__,-1,1>>(N);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 3;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ tau = DUMMY_VAR__;
      current_statement__ = 4;
      tau = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      local_scalar_t__ phi = DUMMY_VAR__;
      current_statement__ = 5;
      phi = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
              1, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> spatial =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(spatial, stan::math::multiply(tau, spatial_raw),
        "assigning variable spatial");
      {
        current_statement__ = 7;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta, 0, 1));
        current_statement__ = 8;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma, 0, 1));
        current_statement__ = 9;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(tau, 0, 1));
        current_statement__ = 10;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(phi, 2, 2));
        {
          int pos = std::numeric_limits<int>::min();
          current_statement__ = 11;
          pos = 1;
          current_statement__ = 25;
          for (int i = 1; i <= N; ++i) {
            current_statement__ = 23;
            if (stan::math::logical_gt(
                  stan::model::rvalue(num_neighbors, "num_neighbors",
                    stan::model::index_uni(i)), 0)) {
              current_statement__ = 14;
              stan::math::validate_non_negative_index("neigh_vals",
                "num_neighbors[i]",
                stan::model::rvalue(num_neighbors, "num_neighbors",
                  stan::model::index_uni(i)));
              Eigen::Matrix<local_scalar_t__,-1,1> neigh_vals =
                Eigen::Matrix<local_scalar_t__,-1,1>::Constant(stan::model::rvalue(
                                                                 num_neighbors,
                                                                 "num_neighbors",
                                                                 stan::model::index_uni(
                                                                   i)),
                  DUMMY_VAR__);
              current_statement__ = 19;
              for (int j = 1; j <=
                   stan::model::rvalue(num_neighbors, "num_neighbors",
                     stan::model::index_uni(i)); ++j) {
                current_statement__ = 16;
                stan::model::assign(neigh_vals,
                  stan::model::rvalue(spatial_raw, "spatial_raw",
                    stan::model::index_uni(
                      stan::model::rvalue(adj, "adj",
                        stan::model::index_uni(pos)))),
                  "assigning variable neigh_vals", stan::model::index_uni(j));
                current_statement__ = 17;
                pos = (pos + 1);
              }
              local_scalar_t__ mean_i = DUMMY_VAR__;
              current_statement__ = 20;
              mean_i = (phi * stan::math::mean(neigh_vals));
              current_statement__ = 21;
              lp_accum__.add(stan::math::normal_lpdf<propto__>(
                               stan::model::rvalue(spatial_raw,
                                 "spatial_raw", stan::model::index_uni(i)),
                               mean_i,
                               stan::math::sqrt((1.0 /
                                 stan::model::rvalue(num_neighbors,
                                   "num_neighbors", stan::model::index_uni(i))))));
            } else {
              current_statement__ = 12;
              lp_accum__.add(stan::math::normal_lpdf<propto__>(
                               stan::model::rvalue(spatial_raw,
                                 "spatial_raw", stan::model::index_uni(i)),
                               0, 1));
            }
          }
        }
        current_statement__ = 27;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(y,
                         stan::math::add(stan::math::multiply(X, beta),
                           spatial), sigma));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "car_model_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__);
      current_statement__ = 1;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(P);
      Eigen::Matrix<local_scalar_t__,-1,1> spatial_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 2;
      spatial_raw = in__.template read<
                      Eigen::Matrix<local_scalar_t__,-1,1>>(N);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 3;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ tau = DUMMY_VAR__;
      current_statement__ = 4;
      tau = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      local_scalar_t__ phi = DUMMY_VAR__;
      current_statement__ = 5;
      phi = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
              1, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> spatial =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(spatial, stan::math::multiply(tau, spatial_raw),
        "assigning variable spatial");
      {
        current_statement__ = 7;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta, 0, 1));
        current_statement__ = 8;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma, 0, 1));
        current_statement__ = 9;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(tau, 0, 1));
        current_statement__ = 10;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(phi, 2, 2));
        {
          int pos = std::numeric_limits<int>::min();
          current_statement__ = 11;
          pos = 1;
          current_statement__ = 25;
          for (int i = 1; i <= N; ++i) {
            current_statement__ = 23;
            if (stan::math::logical_gt(
                  stan::model::rvalue(num_neighbors, "num_neighbors",
                    stan::model::index_uni(i)), 0)) {
              current_statement__ = 14;
              stan::math::validate_non_negative_index("neigh_vals",
                "num_neighbors[i]",
                stan::model::rvalue(num_neighbors, "num_neighbors",
                  stan::model::index_uni(i)));
              Eigen::Matrix<local_scalar_t__,-1,1> neigh_vals =
                Eigen::Matrix<local_scalar_t__,-1,1>::Constant(stan::model::rvalue(
                                                                 num_neighbors,
                                                                 "num_neighbors",
                                                                 stan::model::index_uni(
                                                                   i)),
                  DUMMY_VAR__);
              current_statement__ = 19;
              for (int j = 1; j <=
                   stan::model::rvalue(num_neighbors, "num_neighbors",
                     stan::model::index_uni(i)); ++j) {
                current_statement__ = 16;
                stan::model::assign(neigh_vals,
                  stan::model::rvalue(spatial_raw, "spatial_raw",
                    stan::model::index_uni(
                      stan::model::rvalue(adj, "adj",
                        stan::model::index_uni(pos)))),
                  "assigning variable neigh_vals", stan::model::index_uni(j));
                current_statement__ = 17;
                pos = (pos + 1);
              }
              local_scalar_t__ mean_i = DUMMY_VAR__;
              current_statement__ = 20;
              mean_i = (phi * stan::math::mean(neigh_vals));
              current_statement__ = 21;
              lp_accum__.add(stan::math::normal_lpdf<propto__>(
                               stan::model::rvalue(spatial_raw,
                                 "spatial_raw", stan::model::index_uni(i)),
                               mean_i,
                               stan::math::sqrt((1.0 /
                                 stan::model::rvalue(num_neighbors,
                                   "num_neighbors", stan::model::index_uni(i))))));
            } else {
              current_statement__ = 12;
              lp_accum__.add(stan::math::normal_lpdf<propto__>(
                               stan::model::rvalue(spatial_raw,
                                 "spatial_raw", stan::model::index_uni(i)),
                               0, 1));
            }
          }
        }
        current_statement__ = 27;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(y,
                         stan::math::add(stan::math::multiply(X, beta),
                           spatial), sigma));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "car_model_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> beta =
        Eigen::Matrix<double,-1,1>::Constant(P,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(P);
      Eigen::Matrix<double,-1,1> spatial_raw =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      spatial_raw = in__.template read<
                      Eigen::Matrix<local_scalar_t__,-1,1>>(N);
      double sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      double tau = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      tau = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      double phi = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      phi = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
              1, lp__);
      Eigen::Matrix<double,-1,1> spatial =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(beta);
      out__.write(spatial_raw);
      out__.write(sigma);
      out__.write(tau);
      out__.write(phi);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 6;
      stan::model::assign(spatial, stan::math::multiply(tau, spatial_raw),
        "assigning variable spatial");
      if (emit_transformed_parameters__) {
        out__.write(spatial);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(beta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(P),
        "assigning variable beta");
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> spatial_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(spatial_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(N),
        "assigning variable spatial_raw");
      out__.write(spatial_raw);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 3;
      sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma);
      local_scalar_t__ tau = DUMMY_VAR__;
      current_statement__ = 4;
      tau = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, tau);
      local_scalar_t__ phi = DUMMY_VAR__;
      current_statement__ = 5;
      phi = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, phi);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "beta", "double",
        std::vector<size_t>{static_cast<size_t>(P)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "spatial_raw",
        "double", std::vector<size_t>{static_cast<size_t>(N)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "sigma", "double",
        std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "tau", "double",
        std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "phi", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> beta =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 1;
        beta_flat__ = context__.vals_r("beta");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
          stan::model::assign(beta, beta_flat__[(pos__ - 1)],
            "assigning variable beta", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(beta);
      Eigen::Matrix<local_scalar_t__,-1,1> spatial_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> spatial_raw_flat__;
        current_statement__ = 2;
        spatial_raw_flat__ = context__.vals_r("spatial_raw");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          stan::model::assign(spatial_raw, spatial_raw_flat__[(pos__ - 1)],
            "assigning variable spatial_raw", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(spatial_raw);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 3;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      out__.write_free_lb(0, sigma);
      local_scalar_t__ tau = DUMMY_VAR__;
      current_statement__ = 4;
      tau = context__.vals_r("tau")[(1 - 1)];
      out__.write_free_lb(0, tau);
      local_scalar_t__ phi = DUMMY_VAR__;
      current_statement__ = 5;
      phi = context__.vals_r("phi")[(1 - 1)];
      out__.write_free_lub(0, 1, phi);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"beta", "spatial_raw", "sigma", "tau",
                "phi"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"spatial"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(P)},
                std::vector<size_t>{static_cast<size_t>(N)},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      param_names__.emplace_back(std::string() + "spatial_raw" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "tau");
    param_names__.emplace_back(std::string() + "phi");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "spatial" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
      param_names__.emplace_back(std::string() + "beta" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      param_names__.emplace_back(std::string() + "spatial_raw" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "tau");
    param_names__.emplace_back(std::string() + "phi");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "spatial" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(P) + "},\"block\":\"parameters\"},{\"name\":\"spatial_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"phi\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"spatial\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"beta\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(P) + "},\"block\":\"parameters\"},{\"name\":\"spatial_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"phi\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"spatial\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((P + N) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (N);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((P + N) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (N);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = car_model_model_namespace::car_model_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return car_model_model_namespace::profiles__;
}
#endif